# Password Generator Project
import random

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
           'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
           'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+', '@']

print("Welcome to the PyPassword Generator!")
print("Would you like an auto-generated password or a password you can choose details?")
mode_choice = input("Type 'auto' for autogenerated password or 'manual' to take the command").lower()
# according to the choice of the mode choose et different way
password = []
auto_letter = len(letters)
auto_symbol = len(symbols)
auto_number = len(numbers)
if mode_choice == "auto":
    for n in range(auto_letter):
        password.append(letters[random.randint(0, auto_letter - 1)])
    for k in range(auto_symbol):
        password.append(symbols[random.randint(0, auto_symbol - 1)])
    for i in range(auto_number):
        password.append(numbers[random.randint(0, auto_symbol - 1)])
    suggestion = ""
    for m in range(len(password)):
        suggestion += password[random.randint(0, len(password) - 1)]
    print(f"Your strong password is : {suggestion}")
elif mode_choice == "manual":
    manual_letter = int(input("How many letters would you like in your password?\n"))
    manual_symbol = int(input(f"How many symbols would you like?\n"))
    manual_number = int(input(f"How many numbers would you like?\n"))

    # Eazy Level - Order not randomised:
    password = []
    """for n in range(nr_letters):
        password += letters[random.randint(0, len(letters)-1)]
    for k in range(nr_symbols):
        password += symbols[random.randint(0, len(symbols)-1)]
    for i in range(nr_numbers):
        password += numbers[random.randint(0, len(numbers)-1)]

    print(password)"""

    # Hard Level - Order of characters randomised:
    # e.g. 4 letter, 2 symbol, 2 number = g^2jk8&P
    for n in range(manual_letter):
   #shuffle() function


    print(f"Your strong password is :  {suggestion}")
