fruits = [
    {"nom": "pomme", "indice": "Je suis rouge ou verte, croquante et souvent associée à la gravité"},
    {"nom": "orange", "indice": "Mon nom est aussi une couleur"},
    {"nom": "banane", "indice": "Je suis jaune et courbée"},
    {"nom": "raisin", "indice": "Je pousse en grappes et on me transforme souvent en vin"},
    {"nom": "kiwi", "indice": "Je suis petit, brun et velu à l'extérieur, vert à l'intérieur"},
    {"nom": "mangue", "indice": "Je suis un fruit tropical jaune-orange avec un gros noyau plat"},
    {"nom": "ananas", "indice": "J'ai une couronne de feuilles et une peau écailleuse"},
    {"nom": "cerise", "indice": "Je suis petite, rouge et j'ai une queue"},
    {"nom": "fraise", "indice": "Je suis rouge avec des petites graines sur ma peau"},
    {"nom": "framboise", "indice": "Je suis petite, rouge et composée de plusieurs petites boules"},
    {"nom": "mûre", "indice": "Je ressemble à une framboise mais je suis noire"},
    {"nom": "myrtille", "indice": "Je suis petite, bleue et pousse souvent dans les forêts"},
    {"nom": "pêche", "indice": "J'ai une peau duveteuse et un gros noyau au centre"},
    {"nom": "prune", "indice": "Je suis violette ou rouge, ronde avec un noyau"},
    {"nom": "abricot", "indice": "Je suis orange, veloutée et plus petite qu'une pêche"},
    {"nom": "nectarine", "indice": "Je ressemble à une pêche mais ma peau est lisse"},
    {"nom": "cassis", "indice": "Je suis une petite baie noire utilisée pour faire une liqueur"},
    {"nom": "groseille", "indice": "Je suis une petite baie rouge ou blanche, souvent en grappes"},
    {"nom": "poire", "indice": "J'ai une forme caractéristique, plus large en bas qu'en haut"},
    {"nom": "pamplemousse", "indice": "Je suis un gros agrume, souvent rose à l'intérieur"},
    {"nom": "citron", "indice": "Je suis jaune et très acide"},
    {"nom": "mandarine", "indice": "Je suis comme une petite orange facile à peler"},
    {"nom": "pastèque", "indice": "Je suis très grosse, verte à l'extérieur et rouge à l'intérieur"},
    {"nom": "melon", "indice": "J'ai une peau côtelée et une chair orange ou verte"},
    {"nom": "papaye", "indice": "Je suis un fruit tropical orange avec des graines noires"},
    {"nom": "figue", "indice": "Je suis violette ou verte, en forme de goutte avec des graines croquantes"},
    {"nom": "datte", "indice": "Je suis un fruit séché brun et sucré"},
    {"nom": "grenade", "indice": "J'ai une peau rouge épaisse et plein de graines juteuses à l'intérieur"},
    {"nom": "litchi", "indice": "J'ai une coque rouge rugueuse et une chair translucide"},
    {"nom": "coco", "indice": "J'ai une coque dure brune et un liquide à l'intérieur"},
    {"nom": "carotte", "indice": "Je suis orange, longue et les lapins m'adorent"},
    {"nom": "tomate", "indice": "Je suis rouge, juteuse et souvent utilisée comme légume"},
    {"nom": "courgette", "indice": "Je suis verte, allongée et de la famille des courges"},
    {"nom": "brocoli", "indice": "Je ressemble à un petit arbre vert"},
    {"nom": "chou", "indice": "Je suis rond et formé de nombreuses couches de feuilles"},
    {"nom": "épinard", "indice": "Je suis vert foncé et plein de fer"},
    {"nom": "poivron", "indice": "Je peux être vert, rouge ou jaune et j'ai une forme de cloche"},
    {"nom": "patate", "indice": "Je suis un tubercule brun à l'extérieur et blanc à l'intérieur"},
    {"nom": "aubergine", "indice": "Je suis violette et allongée"},
    {"nom": "radis", "indice": "Je suis petit, rond et rouge avec un goût piquant"}
]

acteurs_celebres = [
    {"nom": "Tom Hanks", "indice": "J'ai joué un homme simple d'esprit qui court à travers l'Amérique et un naufragé sur une île déserte"},
    {"nom": "Meryl Streep", "indice": "Actrice aux multiples Oscars, j'ai incarné Margaret Thatcher et une terrible patronne de magazine de mode"},
    {"nom": "Leonardo DiCaprio", "indice": "J'ai survécu à un naufrage célèbre et j'ai enfin gagné un Oscar pour avoir combattu un ours"},
    {"nom": "Denzel Washington", "indice": "Acteur afro-américain oscarisé, j'ai joué dans 'Malcolm X' et 'Training Day'"},
    {"nom": "Jennifer Lawrence", "indice": "J'ai été Katniss Everdeen dans 'Hunger Games' et j'ai gagné un Oscar pour 'Happiness Therapy'"},
    {"nom": "Robert De Niro", "indice": "J'ai dit 'You talkin' to me?' dans 'Taxi Driver' et j'ai joué un jeune Vito Corleone"},
    {"nom": "Cate Blanchett", "indice": "J'ai été Galadriel dans 'Le Seigneur des Anneaux' et j'ai gagné un Oscar pour avoir joué Katharine Hepburn"},
    {"nom": "Brad Pitt", "indice": "J'ai fondé le 'Fight Club' et j'ai chassé des zombies dans 'World War Z'"},
    {"nom": "Viola Davis", "indice": "Première actrice afro-américaine à avoir remporté les trois plus grandes récompenses d'acteur, j'ai joué dans 'The Help' et 'Fences'"},
    {"nom": "Johnny Depp", "indice": "J'ai été un pirate excentrique et le chapelier fou d'Alice au pays des merveilles"},
    {"nom": "Charlize Theron", "indice": "Actrice sud-africaine, j'ai gagné un Oscar pour mon rôle dans 'Monster' et j'ai conduit dans 'Mad Max: Fury Road'"},
    {"nom": "Morgan Freeman", "indice": "Ma voix distinctive a narré de nombreux documentaires et j'ai joué Dieu dans 'Bruce tout-puissant'"},
    {"nom": "Scarlett Johansson", "indice": "Je suis Black Widow dans l'univers Marvel et j'ai été la voix d'un système d'exploitation dans 'Her'"},
    {"nom": "Anthony Hopkins", "indice": "J'ai joué Hannibal Lecter et récemment le Pape dans 'Les deux papes'"},
    {"nom": "Emma Stone", "indice": "J'ai dansé et chanté dans 'La La Land' et j'ai combattu des zombies dans 'Bienvenue à Zombieland'"},
    {"nom": "Daniel Day-Lewis", "indice": "Acteur britannico-irlandais connu pour mon intense préparation, j'ai gagné trois Oscars dont un pour 'Lincoln'"},
    {"nom": "Julia Roberts", "indice": "Mon sourire est célèbre et j'ai joué une prostitute au grand cœur dans 'Pretty Woman'"},
    {"nom": "Will Smith", "indice": "J'ai commencé comme rappeur, puis j'ai combattu des aliens dans 'Men in Black' et j'ai joué le génie dans 'Aladdin'"},
    {"nom": "Nicole Kidman", "indice": "Actrice australienne, j'ai joué Virginia Woolf dans 'The Hours' et récemment dans la série 'Big Little Lies'"},
    {"nom": "Samuel L. Jackson", "indice": "J'apparais souvent dans les films de Quentin Tarantino et je suis Nick Fury dans l'univers Marvel"}
]

informatique = [
    {"nom": "algorithme", "indice": "Série d'étapes précises pour résoudre un problème ou effectuer une tâche"},
    {"nom": "variable", "indice": "Espace de stockage nommé pour une valeur qui peut changer"},
    {"nom": "fonction", "indice": "Bloc de code réutilisable qui effectue une tâche spécifique"},
    {"nom": "boucle", "indice": "Structure qui répète un bloc de code plusieurs fois"},
    {"nom": "condition", "indice": "Expression qui permet l'exécution sélective de code basée sur une évaluation"},
    {"nom": "tableau", "indice": "Structure de données qui stocke des éléments du même type en séquence"},
    {"nom": "donnée", "indice": "Information brute traitée ou stockée par un ordinateur"},
    {"nom": "fichier", "indice": "Collection de données stockées sous un nom unique sur un support de stockage"},
    {"nom": "réseau", "indice": "Groupe d'ordinateurs et de dispositifs interconnectés pour partager des ressources"},
    {"nom": "serveur", "indice": "Ordinateur ou programme qui fournit des services à d'autres ordinateurs"},
    {"nom": "client", "indice": "Programme ou ordinateur qui demande des services à un serveur"},
    {"nom": "protocole", "indice": "Ensemble de règles régissant la communication entre ordinateurs"},
    {"nom": "cryptographie", "indice": "Science de la protection de l'information par codage"},
    {"nom": "programmation", "indice": "Processus d'écriture d'instructions pour un ordinateur"},
    {"nom": "compilateur", "indice": "Programme qui traduit le code source en code machine"},
    {"nom": "interpréteur", "indice": "Programme qui exécute directement les instructions sans compilation préalable"},
    {"nom": "code", "indice": "Instructions écrites dans un langage de programmation"},
    {"nom": "bug", "indice": "Erreur ou défaut dans un programme informatique"},
    {"nom": "débogage", "indice": "Processus de recherche et de correction des bugs"},
    {"nom": "mémoire", "indice": "Composant qui stocke temporairement les données et les instructions"},
    {"nom": "processeur", "indice": "Composant principal qui exécute les instructions d'un programme"},
    {"nom": "stockage", "indice": "Dispositif ou support pour conserver des données à long terme"},
    {"nom": "système", "indice": "Ensemble de composants matériels et logiciels fonctionnant ensemble"},
    {"nom": "logiciel", "indice": "Programme ou ensemble de programmes exécutés par un ordinateur"},
    {"nom": "matériel", "indice": "Composants physiques d'un système informatique"},
    {"nom": "interface", "indice": "Point de connexion entre deux systèmes ou entre un utilisateur et un système"},
    {"nom": "base de données", "indice": "Collection organisée de données structurées"},
    {"nom": "requête", "indice": "Demande d'information ou d'action adressée à une base de données"},
    {"nom": "heuristique", "indice": "Méthode de résolution de problèmes par l'expérience et l'intuition"},
    {"nom": "machine learning", "indice": "Domaine de l'IA où les systèmes apprennent à partir de données"},
    {"nom": "intelligence artificielle", "indice": "Simulation de l'intelligence humaine par des machines"},
    {"nom": "réalité virtuelle", "indice": "Technologie créant un environnement simulé immersif"},
    {"nom": "robotique", "indice": "Domaine combinant ingénierie et informatique pour créer des robots"},
    {"nom": "nanotechnologie", "indice": "Manipulation de la matière à l'échelle atomique ou moléculaire"}
]

musique = [
    {"nom": "accord", "indice": "Combinaison harmonieuse de plusieurs notes jouées simultanément"},
    {"nom": "batterie", "indice": "Ensemble d'instruments à percussion comprenant généralement des tambours et des cymbales"},
    {"nom": "basse", "indice": "Instrument ou voix produisant les sons les plus graves dans un ensemble musical"},
    {"nom": "chant", "indice": "Production de sons musicaux avec la voix humaine"},
    {"nom": "chanson", "indice": "Composition musicale courte avec des paroles, destinée à être chantée"},
    {"nom": "chœur", "indice": "Ensemble de chanteurs interprétant une œuvre musicale"},
    {"nom": "chorale", "indice": "Groupe organisé de chanteurs, souvent amateurs"},
    {"nom": "compositeur", "indice": "Personne qui crée des œuvres musicales originales"},
    {"nom": "concert", "indice": "Représentation musicale publique"},
    {"nom": "contrebasse", "indice": "Le plus grand et le plus grave des instruments à cordes frottées"},
    {"nom": "couplet", "indice": "Partie d'une chanson qui alterne avec le refrain"},
    {"nom": "cymbale", "indice": "Instrument de percussion consistant en un disque métallique"},
    {"nom": "djembé", "indice": "Tambour africain en forme de calice, joué à mains nues"},
    {"nom": "flûte", "indice": "Instrument à vent en bois, avec un son doux et aigu"},
    {"nom": "guitare", "indice": "Instrument à cordes pincées avec une caisse de résonance"},
    {"nom": "harmonica", "indice": "Petit instrument à vent à anches libres"},
    {"nom": "harmonie", "indice": "Combinaison agréable de sons musicaux"},
    {"nom": "harpe", "indice": "Grand instrument à cordes pincées, de forme triangulaire"},
    {"nom": "instrument", "indice": "Objet conçu pour produire des sons musicaux"},
    {"nom": "jazz", "indice": "Genre musical né aux États-Unis, caractérisé par l'improvisation"},
    {"nom": "lyrique", "indice": "Relatif à la poésie chantée ou à l'expression des émotions en musique"},
    {"nom": "mélodie", "indice": "Succession de notes formant une phrase musicale reconnaissable"},
    {"nom": "musicien", "indice": "Personne qui joue d'un instrument ou compose de la musique"},
    {"nom": "octave", "indice": "Intervalle entre deux notes de même nom, l'une ayant une fréquence double de l'autre"},
    {"nom": "orchestre", "indice": "Ensemble d'instrumentistes jouant différents instruments"},
    {"nom": "partition", "indice": "Notation écrite d'une composition musicale"},
    {"nom": "piano", "indice": "Instrument à cordes frappées avec un clavier"},
    {"nom": "quatuor", "indice": "Ensemble musical de quatre instruments ou voix"},
    {"nom": "refrain", "indice": "Partie d'une chanson qui se répète après chaque couplet"},
    {"nom": "rythme", "indice": "Organisation du temps dans la musique"},
    {"nom": "saxophone", "indice": "Instrument à vent en métal, à anche simple"},
    {"nom": "solfège", "indice": "Méthode d'apprentissage de la lecture et de l'écriture musicale"},
    {"nom": "solo", "indice": "Passage musical joué ou chanté par un seul interprète"},
    {"nom": "sonate", "indice": "Composition pour un ou deux instruments, généralement en plusieurs mouvements"},
    {"nom": "symphonie", "indice": "Composition musicale élaborée pour orchestre, généralement en quatre mouvements"},
    {"nom": "tambour", "indice": "Instrument de percussion à membrane tendue sur un fût"},
    {"nom": "tempo", "indice": "Vitesse d'exécution d'un morceau musical"},
    {"nom": "ténor", "indice": "Voix masculine la plus aiguë dans la tessiture normale"},
    {"nom": "trombone", "indice": "Instrument à vent de la famille des cuivres, avec une coulisse"},
    {"nom": "trompette", "indice": "Instrument à vent de la famille des cuivres, avec trois pistons"},
    {"nom": "ukulélé", "indice": "Petit instrument à cordes pincées originaire d'Hawaï"},
    {"nom": "violon", "indice": "Instrument à cordes frottées le plus aigu de sa famille"},
    {"nom": "violoncelle", "indice": "Instrument à cordes frottées plus grand que l'alto, plus petit que la contrebasse"},
    {"nom": "voix", "indice": "Son produit par les cordes vocales humaines"},
    {"nom": "maestro", "indice": "Terme respectueux pour désigner un grand musicien ou chef d'orchestre"},
    {"nom": "orchestrateur", "indice": "Personne qui arrange une composition pour être jouée par un orchestre"},
    {"nom": "batteur", "indice": "Musicien qui joue de la batterie"},
    {"nom": "chef d'orchestre", "indice": "Personne qui dirige un orchestre ou un ensemble musical"}
]

animaux = [
    {"nom": "éléphant", "indice": "Je suis grand, j'ai de grandes oreilles et une longue trompe"},
    {"nom": "pingouin", "indice": "Je porte un smoking naturel et je glisse sur le ventre"},
    {"nom": "girafe", "indice": "J'ai un très long cou et des taches sur tout le corps"},
    {"nom": "caméléon", "indice": "Je peux changer de couleur pour me fondre dans le décor"},
    {"nom": "kangourou", "indice": "Je me déplace en sautant et j'ai une poche sur le ventre"},
    {"nom": "paresseux", "indice": "Je vis à l'envers dans les arbres et je suis très, très lent"},
    {"nom": "ornithorynque", "indice": "J'ai un bec de canard, une queue de castor et je ponds des œufs"},
    {"nom": "narval", "indice": "Je suis une baleine avec une longue corne sur la tête"},
    {"nom": "axolotl", "indice": "Je suis un petit animal aquatique qui ressemble à un Pokémon"},
    {"nom": "panda", "indice": "Je suis noir et blanc, j'adore manger du bambou"},
    {"nom": "flamant rose", "indice": "Je dors debout sur une patte et ma couleur vient de ce que je mange"},
    {"nom": "hippopotame", "indice": "Je suis gros, j'aime l'eau et mon nom signifie 'cheval de rivière'"},
    {"nom": "toucan", "indice": "J'ai un bec énorme et coloré, plus grand que ma tête"},
    {"nom": "manchot", "indice": "Je vis dans le froid, je marche comme un gentleman et je couve mon œuf sur mes pieds"},
    {"nom": "koala", "indice": "Je vis en Australie, je dors beaucoup et je mange des feuilles d'eucalyptus"},
    {"nom": "tatou", "indice": "Je porte une armure naturelle et je peux me rouler en boule"},
    {"nom": "lémur", "indice": "J'ai de grands yeux et une longue queue rayée, je vis à Madagascar"},
    {"nom": "colibri", "indice": "Je suis minuscule, je peux voler en arrière et mes ailes battent très vite"},
    {"nom": "okapi", "indice": "J'ai des rayures comme un zèbre mais je suis de la famille de la girafe"},
    {"nom": "blob", "indice": "Je n'ai ni cerveau ni estomac, mais je peux résoudre des problèmes"},
    {"nom": "poisson-clown", "indice": "Je vis dans les anémones de mer et un film d'animation m'a rendu célèbre"},
    {"nom": "chouette", "indice": "Je peux tourner ma tête presque complètement et je chasse la nuit"},
    {"nom": "suricate", "indice": "Je vis en groupe et j'adore me tenir debout pour surveiller les alentours"},
    {"nom": "dragon de Komodo", "indice": "Je suis le plus grand lézard du monde et je vis sur une île indonésienne"},
    {"nom": "pieuvre", "indice": "J'ai huit bras, trois cœurs et je peux changer de couleur"}
]
